language: java
sudo: false

matrix:
  include:
    - env: JDK='Oracle JDK 8'
      jdk: oraclejdk8

before_install:
- chmod +x ./gradlew
script:
- echo PATH = ${PATH}
- echo JAVA_HOME = ${JAVA_HOME}
- java -version
- "./gradlew build --info"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  user: "taowenyin"
  password: "05200902"
  file: build/libs/ElectricIOTDaemon.jar
  skip_cleanup: true